In [3]:
import pandas as pd
df_prod=  pd.read_csv('data//products.csv')
df_prod.head()

,product_id,product_name,category,unit_of_measure,unit_price,criticality,status
0,P-101,Smart Sensor Module,Electronics,units,2500,High,Active
1,P-102,Industrial Cable,Electrical,meters,300,Medium,Active
2,P-103,Control Valve,Mechanical,units,4200,High,Active
3,P-104,Packaging Film,Packaging,rolls,900,Low,Active
4,P-105,Battery Pack,Electronics,units,3200,High,Active

In [5]:
df_sal =  pd.read_csv('data//sales_history.csv')
df_sal[df_sal["product_id"] == 'P-101']

,date,product_id,region,units_sold,revenue,promotion_flag,season,event_flag
0,2026-02-26,P-101,North,79,197500.0,0,Normal,0
1,2026-02-27,P-101,North,119,297500.0,0,Normal,0
2,2026-02-28,P-101,North,90,225000.0,0,Normal,0
3,2026-03-01,P-101,North,64,160000.0,0,Normal,0
4,2026-03-02,P-101,North,83,207500.0,0,Normal,0
...,...,...,...,...,...,...,...,...
355,2026-05-22,P-101,West,131,327500.0,0,Peak,0
356,2026-05-23,P-101,West,108,270000.0,0,Peak,0
357,2026-05-24,P-101,West,120,300000.0,0,Peak,0
358,2026-05-25,P-101,West,119,297500.0,0,Peak,0
359,2026-05-26,P-101,West,70,175000.0,0,Peak,0

In [4]:
df_inv = pd.read_csv('inventory.csv')
df_inv.head()

,inventory_id,product_id,warehouse_id,region,current_stock,safety_stock,reorder_point,last_updated
0,INV-001,P-101,WH-EAST-01,East,645,49,433,2026-05-26
1,INV-002,P-101,WH-NORTH-01,North,641,55,568,2026-05-26
2,INV-003,P-101,WH-SOUTH-01,South,80,72,696,2026-05-26
3,INV-004,P-101,WH-WEST-01,West,718,48,453,2026-05-26
4,INV-005,P-102,WH-EAST-01,East,1478,89,926,2026-05-26